version: "3"
volumes:
  postgis-data:
  chaches-data:
services:

  banner:
    image: banner
    networks:
      - default
    volumes:
      - ./config/docker-config.yaml:/config.yaml
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/config.yaml
    depends_on:
      - banner-bd
      - chaches
    restart: on-failure
  
  banner-bd:
    image: postgres:16
    expose:
      - "5432"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./config/services/postgres.conf:/etc/postgresql/postgresql.conf
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  
  chaches:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - chaches-data:/data
    restart: always
networks:
  default:
    driver: bridge